CRUD/urls.py
from django.contrib import admin  
from django.urls import path  
from student import views



urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

student/models.py
from django.db import models

class Student(models.Model):  
    sid = models.CharField(max_length=20)  
    sname = models.CharField(max_length=100)  
    semail = models.EmailField()  
    scontact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "student"  

student/forms.py
from django import forms  
from student.models import Student  
class StudentForm(forms.ModelForm):  
    class Meta:  
        model = Student  
        fields = "__all__"  

student/views.py
from django.shortcuts import render, redirect  
from student.forms import StudentForm  
from student.models import Student  
# Create your views here.



def emp(request):  
    if request.method == "POST":  
        form = StudentForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = StudentForm()  
    return render(request,'index.html',{'form':form})

def show(request):  
    students = Student.objects.all()  
    return render(request,"show.html",{'students':students})

def edit(request, id):  
    student = Student.objects.get(id=id)  
    return render(request,'edit.html', {'student':student})

def update(request, id):  
    student = Student.objects.get(id=id)  
    form = StudentForm(request.POST, instance = student)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'student': student})  
def destroy(request, id):  
    student = Student.objects.get(id=id)  
    student.delete()  
    return redirect("/show")  

student/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'style.css' %}"/>  
</head>  
<body 
style="background-color:gainsboro;">  <center>
<form method="POST" class="post-form" action="/update/{{student.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student ID:</label>  
    <div class="col-sm-4">  
        <input type="text" name="sid" id="id_sid" required maxlength="20" value="{{ student.sid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="sname" id="id_sname" required maxlength="100" value="{{ student.sname }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="semail" id="id_semail" required maxlength="254" value="{{ student.semail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="scontact" id="id_scontact" required maxlength="15" value="{{ student.scontact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</center>
</body>  
</html>  

student/templates/index.html
<!DOCTYPE html>  
<html lang="en"> 
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"> 
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'style.css' %}"/>  
</head>  
<body style="background-color:gainsboro;"> 
<center>


<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Id:</label>  
    <div class="col-sm-4">  
      {{ form.sid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Name:</label>  
    <div class="col-sm-4">  
      {{ form.sname }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Email:</label>  
    <div class="col-sm-4">  
      {{ form.semail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Contact:</label>  
    <div class="col-sm-4">  
      {{ form.scontact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</center>
</body>  
</html>  

student/templates/show.html
<!DOCTYPE html>  
<html lang="en"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"> 
<head>  
    <meta charset="UTF-8">  
    <title>Student Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'style.css' %}"/>  
</head> 
 
<style>
    table {
        border: 8px outset;
        border-radius: 10px;
        border-spacing: 10px;
        padding: 20px;
        margin-left: auto;
        margin-right: auto;
    }

    th,
    td {
        padding: 5px;
        border: 1px solid;
    }
</style>
<body style="background-color:gainsboro;">   
    <h2 style="text-align:center"> Student Information </h2>
    <center>
<table class="table table-dark table-striped">  
    <thead class="thead-dark">  
    <tr>  
        <th>Student ID</th>  
        <th>Student Name</th>  
        <th>Student Email</th>  
        <th>Student Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for student in students %}  
    <tr>  
        <td>{{ student.sid }}</td>  
        <td>{{ student.sname }}</td>  
        <td>{{ student.semail }}</td>  
        <td>{{ student.scontact }}</td>  
        <td><center>
              
            <a href="/edit/{{ student.id }}"><button type="button" class="btn btn-primary">Edit</button></a>  
            <a href="/delete/{{ student.id }}"><button type="button" class="btn btn-danger">Delete</button></a>  
       
       </center> </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  </center>
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  